name: zookeeper # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '3.6.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  init:
    command: bin/zkServer-initialize.sh --config /snap/zookeeper/current/conf
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-8-openjdk-amd64/jre
  cli:
    command: bin/zkCli.sh --config /snap/zookeeper/current/conf
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-8-openjdk-amd64/jre
  daemon:
    command: bin/zkServer.sh --config /snap/zookeeper/current/conf start
    plugs: [network, network-bind, removable-media]
    install-mode: enable
    daemon: forking
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-8-openjdk-amd64/jre
      ZOO_LOG_DIR: /var/snap/zookeeper/common
    stop-command: bin/zkServer.sh --config /snap/zookeeper/current/conf stop
  status:
    command: bin/zkServer.sh --config /snap/zookeeper/current/conf status
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-8-openjdk-amd64/jre

parts:
  zookeeper:
    plugin: nil
    source: https://dlcdn.apache.org/zookeeper/zookeeper-${SNAPCRAFT_PROJECT_VERSION}/apache-zookeeper-${SNAPCRAFT_PROJECT_VERSION}-bin.tar.gz
    stage-packages:
    - openjdk-8-jre-headless
    override-build: |-
      snapcraftctl build
      sed -i "s:dataDir=/tmp/zookeeper:dataDir=/var/snap/zookeeper/common:g" conf/zoo_sample.cfg
      cp conf/zoo_sample.cfg conf/zoo.cfg
      cp -r ./* $SNAPCRAFT_PART_INSTALL