name: zookeeper
base: core22
version: '3.6.3'
summary: Apache Zookeeper in a snap.
description: |
  ZooKeeper is a centralized service for maintaining configuration 
  information, naming, providing distributed synchronization, and 
  providing group services.

grade: devel
confinement: devmode

apps:
  init:
    command: bin/zkServer-initialize.sh --config /snap/zookeeper/current/conf
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-8-openjdk-amd64/jre
  cli:
    command: bin/zkCli.sh --config /snap/zookeeper/current/conf
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-8-openjdk-amd64/jre
  daemon:
    command: bin/zkServer.sh --config /snap/zookeeper/current/conf start
    plugs: [network, network-bind, removable-media]
    install-mode: enable
    daemon: forking
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-8-openjdk-amd64/jre
      ZOO_LOG_DIR: /var/snap/zookeeper/common
    stop-command: bin/zkServer.sh --config /snap/zookeeper/current/conf stop
  status:
    command: bin/zkServer.sh --config /snap/zookeeper/current/conf status
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-8-openjdk-amd64/jre

parts:
  zookeeper:
    plugin: nil
    source: https://dlcdn.apache.org/zookeeper/zookeeper-${SNAPCRAFT_PROJECT_VERSION}/apache-zookeeper-${SNAPCRAFT_PROJECT_VERSION}-bin.tar.gz
    stage-packages:
    - openjdk-8-jre-headless
    override-build: |-
      snapcraftctl build
      sed -i "s:dataDir=/tmp/zookeeper:dataDir=/var/snap/zookeeper/common:g" conf/zoo_sample.cfg
      cp conf/zoo_sample.cfg conf/zoo.cfg
      cp -r ./* $SNAPCRAFT_PART_INSTALL